version: "3.9"

services:
  text-service:
    build:
      context: ../text_model
      dockerfile: Dockerfile
    networks: [inference]
    env_file:
      - ../.env
    ports:
      - "8001:80"

  image-service:
    build:
      context: ../image_model
      dockerfile: Dockerfile
    networks: [inference]
    env_file:
      - ../.env
    ports:
      - "8002:80"

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"            # only public port
    depends_on:
      - text-service
      - image-service
    networks: [inference]
    env_file:
      - ../.env

  prom:
    image: prom/prometheus:v2.52.0
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    networks: [inference]

networks:
  inference:
    driver: bridge

volumes:
  prom_data:
